# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/opportunityhub
spring.data.mongodb.database=opportunityhub

# Server port
server.port=8080

# App name
spring.application.name=OpportunityHub

# Logging
logging.level.com.opportunityhub=DEBUG
